import {useState,useRef} from 'react';
import {createBackup,decodeBackup,restoreBackup} from './backup';
import {download} from './api';
import type {State} from './store';
export function BackupPanel(){
 const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[prepared,setPrepared]=useState<{state:State,images:Map<string,Blob>}|null>(null);
 const picker=useRef<HTMLInputElement>(null);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="panel"><h2>バックアップ・復元</h2><label className="field">バックアップ用パスワード<input type="password" minLength={8} autoComplete="new-password" value={password} onChange={e=>{setPassword(e.target.value);setFile(null);setPrepared(null)}} placeholder="8文字以上"/></label><p className="muted">写真・住所・回答・履歴をまとめて暗号化します。復元には同じパスワードが必要です。</p>{error&&<p className="alert" role="alert">{error}</p>}<div className="actions"><button className="primary" disabled={busy||password.length<8} onClick={()=>void run(async()=>{const blob=await createBackup(password);setFile(new File([blob],'ouboken-backup-'+new Date().toISOString().slice(0,10)+'.ouboken',{type:blob.type}));setPrepared(null)})}>{busy?'処理中…':'バックアップを作る'}</button><button className="secondary" disabled={busy||password.length<8} onClick={()=>picker.current?.click()}>復元ファイルを選ぶ</button></div><input ref={picker} type="file" accept=".ouboken,application/octet-stream" hidden onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{setPrepared(await decodeBackup(file,password));setFile(null)})}}/>{file&&<div className="panel-footer"><button className="primary" onClick={()=>void run(async()=>{if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'Oubokenバックアップ'});return}catch(e){if((e as Error).name==='AbortError')return}}download(file,file.name)})}>ファイルに保存</button></div>}{prepared&&<div className="panel-footer"><p>{prepared.state.tickets.length}枚を復元します。このPWAの現在の台帳を置き換えます。</p><button className="primary" disabled={busy} onClick={()=>void run(async()=>{await restoreBackup(prepared);location.reload()})}>このバックアップで置き換える</button><button className="secondary" onClick={()=>setPrepared(null)}>キャンセル</button></div>}</section>;
}
