import {useRef,useEffect,useState} from 'react';
import {api} from './api';
export const statusLabels:Record<string,string>={review:'要確認',ready:'確認済み',prepared:'出力済み',done:'応募済み（手動）',unknown:'結果不明'};
export function BatchStatusDialog({tickets,busy,error,onCancel,onSubmit}:{tickets:{id:string,code:string,filename:string}[],busy:boolean,error:string,onCancel:()=>void,onSubmit:(state:string)=>void}){
 const ref=useRef<HTMLDialogElement>(null);const [target,setTarget]=useState('done'),[checking,setChecking]=useState(true),[problem,setProblem]=useState(''),[changed,setChanged]=useState(0);
 useEffect(()=>{ref.current?.showModal()},[]);
 useEffect(()=>{let alive=true;setChecking(true);setProblem('');setChanged(0);api('/tickets/status/preview','POST',{ids:tickets.map(t=>t.id),state:target}).then(result=>{if(alive)setChanged(result.changed)}).catch(e=>{if(alive)setProblem(e.message)}).finally(()=>{if(alive)setChecking(false)});return()=>{alive=false}},[target,tickets]);
 return <dialog ref={ref} className="shortcut-dialog" aria-labelledby="batch-title" onCancel={e=>{if(busy)e.preventDefault();else onCancel()}}><div className="shortcut-dialog-body"><h2 id="batch-title">{tickets.length}枚のステータスを変更</h2><label className="field">変更後のステータス<select value={target} disabled={busy} onChange={e=>setTarget(e.target.value)}>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{target==='done'&&<p className="muted">応募を終えた券を、手動で記録します。</p>}<details className="batch-codes"><summary>選択した応募券</summary>{tickets.map(t=><p className="serial" key={t.id}>{t.code||t.filename}</p>)}</details>{(error||problem)&&<p role="alert" className="alert">{error||problem}</p>}{checking&&<p className="muted" role="status">確認中…</p>}{!checking&&!problem&&!changed&&<p className="muted">すべて同じステータスです。</p>}<div className="delete-actions"><button className="secondary" disabled={busy} onClick={onCancel}>キャンセル</button><button className="primary" disabled={busy||checking||!!problem||!changed} onClick={()=>onSubmit(target)}>{busy?'変更中…':checking||problem?'変更する':changed+'枚を変更する'}</button></div></div></dialog>;
}
