import React, {useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Ticket, List, UserRound, MessageSquareText, Settings2, Plus, FolderOpen, Search, ChevronDown, ChevronRight, Copy, Check, ArrowUpRight, Download, MoreHorizontal, Sparkles, X, LoaderCircle, ArrowLeft, Trash2} from 'lucide-react';
import './style.css';

type Answers = Record<string,string|string[]>;
type Question={id:string,label:string,type:string,options?:string[],generate?:boolean};
type Payload={profile:Record<string,string>,answers:Answers,character:string,code:string,code2:string};
type TicketData={id:string,filename:string,image:string,crop:string,code:string,code2:string,state:string,character:string,approved:number,answers:Answers,answer_overrides?:Answers,character_override?:string,note:string,created:string,ocr:{candidates?:{text:string}[]},payload?:Payload|null,history?:{state:string,note:string,created:string,snapshot?:Payload|null}[]};
type Boot={token:string,profile:Record<string,string>,survey:{answers?:Answers,character?:string,notes?:Record<string,string>},llm:{model:string,has_key:boolean},schema:{profile:[string,string,boolean][],selects:Record<string,string[]>,questions:Question[],characters:string[],url:string,code2:string}};
import {api,imageUrl,exportZip,exportCsv,download as saveDownload} from './api';
import {BackupPanel} from './BackupPanel';
import {PwaStatus,startPwa} from './PwaStatus';
import {StoragePanel,useStorageWarnings} from './StoragePanel';
import {LlmPanel} from './LlmPanel';
import {llmConfig} from './llm';
// Serialize writes so a slow response cannot overwrite a newer edit.
function useAutosave(value:unknown, dirty:boolean, ready:boolean, write:(value:any)=>Promise<void>, clean:()=>void){
 const serialized=JSON.stringify(value);
 const latest=useRef({serialized,dirty,ready,write,clean});
 latest.current={serialized,dirty,ready,write,clean};
 const saved=useRef(serialized), flight=useRef<Promise<void>|null>(null);
 const [status,setStatus]=useState(''),[failure,setFailure]=useState('');
 const flush=async():Promise<void>=>{
  if(flight.current){await flight.current;return flush()}
  if(!latest.current.ready||!latest.current.dirty)return;
  if(saved.current===latest.current.serialized){latest.current.clean();return}
  const task=(async()=>{
   setStatus('保存中…');setFailure('');
   try{
    while(latest.current.ready&&latest.current.dirty&&saved.current!==latest.current.serialized){
     const snapshot=latest.current.serialized;
     await latest.current.write(JSON.parse(snapshot));saved.current=snapshot;
    }
    latest.current.clean();setStatus('自動保存済み');
   }catch(e){setStatus('保存できませんでした');setFailure((e as Error).message);throw e}
  })();
  flight.current=task;
  try{await task}finally{flight.current=null}
 };
 useEffect(()=>{
  if(!dirty){saved.current=serialized;return}
  setStatus('保存待ち…');
  const timer=setTimeout(()=>{void flush().catch(()=>{})},600);
  return()=>clearTimeout(timer);
 },[serialized,dirty,ready]);
 useEffect(()=>{
  const warn=(e:BeforeUnloadEvent)=>{if(latest.current.dirty){e.preventDefault();e.returnValue=''}};
  const hide=()=>{if(document.visibilityState==='hidden')void flush().catch(()=>{})};
  window.addEventListener('beforeunload',warn);document.addEventListener('visibilitychange',hide);
  return()=>{window.removeEventListener('beforeunload',warn);document.removeEventListener('visibilitychange',hide)};
 },[]);
 return {flush,status,failure};
}
function SaveStatus({save}:{save:ReturnType<typeof useAutosave>}){return <div className="save-status" role="status"><span>{save.status}</span>{save.failure&&<><span className="save-error">{save.failure}</span><button className="secondary" onClick={()=>void save.flush().catch(()=>{})}>再試行</button></>}</div>}
const states:Record<string,string>={review:'要確認',ready:'確認済み',prepared:'出力済み',done:'応募済み（手動）',unknown:'結果不明'};
function App(){
 const uploadInput=useRef<HTMLInputElement>(null),detailFlush=useRef<null|(()=>Promise<void>)>(null);
 const [boot,setBoot]=useState<Boot|null>(null),[tickets,setTickets]=useState<TicketData[]>([]),[page,setPage]=useState('home'),[open,setOpen]=useState('');
 const [profile,setProfile]=useState<Record<string,string>>({}),[answers,setAnswers]=useState<Answers>({}),[character,setCharacter]=useState(''),[notes,setNotes]=useState<Record<string,string>>({});
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[deleteTarget,setDeleteTarget]=useState<TicketData|null>(null);
 const [job,setJob]=useState<{id:string,done:number,total:number}|null>(null),[exportIds,setExportIds]=useState<string[]|null>(null),[reviewIds,setReviewIds]=useState<string[]>([]),[writingIds,setWritingIds]=useState<string[]>([]),[focusField,setFocusField]=useState('');
 const [search,setSearch]=useState(''),[filter,setFilter]=useState(''),[draft,setDraft]=useState<{id:string,before:string,after:string}|null>(null),[variants,setVariants]=useState<Answers[]>([]);
 const warnings=useStorageWarnings();
 const [duplicates,setDuplicates]=useState<{filename:string,code:string,existing:string}[]>([]);
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),3000)};
 const refresh=async()=>setTickets(await api('/tickets'));
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{void run(async()=>{const b=await api('/bootstrap');if(b.job)setJob(b.job);setBoot(b);setProfile(b.profile);setAnswers(b.survey.answers||{});setNotes(b.survey.notes||{});setCharacter(b.survey.character||'');await refresh();setVariants((await api('/drafts')).variants)})},[]);
 const auto=useAutosave({profile,survey:{answers,character,notes}},dirty,!!boot,async value=>{
  await api('/settings','PUT',value);setBoot(b=>b?{...b,profile:value.profile,survey:value.survey,llm:b.llm}:b);await refresh();
 },()=>setDirty(false));
 const navigate=(target:string,field='')=>run(async()=>{await auto.flush();await detailFlush.current?.();setOpen('');if(target==='list'){setSearch('');setFilter('')}setPage(target);setFocusField(field);window.scrollTo({top:0,behavior:'instant'})});
 useEffect(()=>{if(focusField){document.getElementById(focusField)?.scrollIntoView({block:'center'});document.getElementById(focusField)?.focus()}},[page,focusField]);
 useEffect(()=>{if(!job)return;const timer=setInterval(async()=>{try{const r=await api('/jobs/'+job.id);setJob(r.status==='done'?null:{id:job.id,done:r.done,total:r.total});await refresh();if(r.status==='done')setDuplicates(r.results.filter((v:any)=>v.duplicate));if(r.status==='done'&&r.errors.length)setError(r.errors.map((e:{filename:string,message:string})=>e.filename+': '+e.message).join(' / '))}catch(e){setError((e as Error).message);setJob(null)}},1500);return()=>clearInterval(timer)},[job?.id]);
 const upload=(files:FileList|null)=>{if(!files?.length)return;void run(async()=>{const data=new FormData();Array.from(files).forEach(f=>data.append('files',f));const r=await api('/upload','POST',data);setDuplicates([]);setJob({id:r.id,done:0,total:files.length})})};
 const startReview=(ids?:string[])=>run(async()=>{await auto.flush();await detailFlush.current?.();setReviewIds(ids||tickets.filter(t=>!t.approved&&!['done','unknown'].includes(t.state)).map(t=>t.id));setPage('review');window.scrollTo({top:0,behavior:'instant'})});
 const startWriting=()=>run(async()=>{await auto.flush();await detailFlush.current?.();setWritingIds(tickets.filter(t=>t.approved&&!['done','unknown'].includes(t.state)).map(t=>t.id));setPage('writing');window.scrollTo({top:0,behavior:'instant'})});
 const startExport=(ids=tickets.map(t=>t.id))=>run(async()=>{await auto.flush();await detailFlush.current?.();setExportIds(ids)});
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);notify('コピーしました')}catch{setError('コピーできませんでした。文字を長押ししてコピーしてください。')}};
 const requestDelete=(ticket:TicketData)=>run(async()=>{await auto.flush();await detailFlush.current?.();setDeleteTarget(ticket)});
 const deleteTicket=()=>run(async()=>{if(!deleteTarget)return;await detailFlush.current?.();await api('/tickets/'+deleteTarget.id,'DELETE');if(open===deleteTarget.id)setOpen('');setDeleteTarget(null);await refresh();notify('応募券を削除しました')});
 const toggleTicket=(id:string)=>run(async()=>{await detailFlush.current?.();setOpen(open===id?'':id);window.scrollTo({top:0,behavior:'instant'})});
 const polish=(id:string)=>run(async()=>{if(!boot?.llm.has_key){setError('設定でOpenAI APIキーを入力してください');setPage('settings');return}const before=String(answers[id]||'');if(!before.trim()){setError('文章の元になる感想・要望を入力してください');return}await auto.flush();const result=await api('/generate','POST',{notes:{[id]:before},count:1,max_length:250});setDraft({id,before,after:result.variants[0][id]})});
 if(!boot)return <div className="loading">{error||'読み込み中…'}</div>;
 const pending=tickets.filter(t=>!t.approved&&!['done','unknown'].includes(t.state)),active=tickets.filter(t=>!['done','unknown'].includes(t.state)),confirmed=active.filter(t=>t.approved);
 const missingProfile=boot.schema.profile.filter(([id,_,required])=>{const value=profile[id]||'';return required&&!value.trim()||value&&(id==='c_q1_left'&&!/^\d{3}$/.test(value)||id==='c_q1_right'&&!/^\d{4}$/.test(value)||id.startsWith('c_q9_')&&!new RegExp(id.endsWith('areacode')?'^\\d{1,5}$':'^\\d{1,4}$').test(value)||id==='c_q17'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))}).length;
 const visible=tickets.filter(t=>(!filter||t.state===filter)&&`${t.code} ${t.filename} ${t.character}`.toLowerCase().includes(search.toLowerCase()));
 const title=page==='home'?'応募券':page==='list'?(open?'応募券の詳細':'応募券一覧・履歴'):page==='profile'?'応募者情報':page==='survey'?'共通アンケート':page==='writing'?'コードごとの自由記述':page==='settings'?'設定':'コードの確認';
 return <div className="app simple-app"><aside><div className="brand"><Ticket size={22}/><b>Ouboken</b><small className="subtle">PWA試作</small></div><button className="header-settings" aria-label="設定" onClick={()=>navigate('settings')}><Settings2 size={20}/></button></aside><div className="main"><main>
 {page!=='home'&&<button className="back-link" disabled={busy} onClick={()=>page==='list'&&open?toggleTicket(open):navigate('home')}><ArrowLeft size={18}/>前に戻る</button>}
 <div className="page-title"><h1>{title}</h1>{page==='home'&&<button className="secondary add-photo" disabled={busy||!!job} onClick={()=>uploadInput.current?.click()}><Plus size={19}/>写真</button>}</div>
 {error&&<div role="alert" className="alert">{error}<button aria-label="エラーを閉じる" onClick={()=>setError('')}><X size={16}/></button></div>}
 <input ref={uploadInput} type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={e=>{upload(e.target.files);e.target.value=''}}/>
 {page==='home'&&<>
 {warnings.length>0&&<div className="storage-warning" role="alert">{warnings.map(m=><p key={m}>{m}</p>)}</div>}
 {duplicates.length>0&&<div className="duplicate-notice" role="status"><div><strong>重複を{duplicates.length}件検出しました</strong><button aria-label="重複通知を閉じる" onClick={()=>setDuplicates([])}><X size={16}/></button></div><details><summary>重複した写真・コード</summary>{duplicates.map((d,i)=><p key={i}>{d.filename}{d.code&&<>：<span className="serial">{d.code}</span></>}<small>登録済み：{d.existing}</small></p>)}</details></div>}
 <section className="home-work"><div className="home-count"><strong>{tickets.length}<small>枚</small></strong><span>{pending.length?`未確認 ${pending.length}枚`:`確認済み ${active.length}枚`}</span></div>
 {job?<div className="progress"><LoaderCircle className="spin" size={18}/>写真を読み取り中 {job.done} / {job.total||'—'}</div>:!tickets.length?<button className="primary" onClick={()=>uploadInput.current?.click()}><Plus size={20}/>写真を追加</button>:<div className="workflow-steps">
 <button className="workflow-step" disabled={busy||!pending.length} onClick={()=>startReview()}><span className="step-number">1</span><span className="step-copy"><strong>コード確認</strong><small>{pending.length?`未確認 ${pending.length}枚`:'確認済み'}</small></span>{pending.length?<ChevronRight size={20}/>:<Check size={20}/>}</button>
 <button className="workflow-step" disabled={busy||!confirmed.length} onClick={()=>startWriting()}><span className="step-number">2</span><span className="step-copy"><strong>コードごとの自由記述</strong><small>{confirmed.length?`${confirmed.length}枚を編集`:'先にコードを確認'}</small></span><ChevronRight size={20}/></button>
 <button className="workflow-step" disabled={busy||!active.length} onClick={()=>startExport()}><span className="step-number">3</span><span className="step-copy"><strong>ZIPにまとめる</strong></span><Download size={20}/></button>
 </div>}

 </section><BackupPanel home disabled={busy||!!job} flush={async()=>{await auto.flush();await detailFlush.current?.()}}/><section className="home-links"><button onClick={()=>navigate('profile')}><UserRound size={20}/><span>応募者情報</span><small>{missingProfile?`要確認 ${missingProfile}項目`:'登録済み'}</small><ChevronRight size={18}/></button><button onClick={()=>navigate('survey')}><MessageSquareText size={20}/><span>共通アンケート</span><small>{character||'未設定'}</small><ChevronRight size={18}/></button><button onClick={()=>navigate('list')}><List size={20}/><span>応募券一覧・履歴</span><ChevronRight size={18}/></button></section>
 <details className="home-other"><summary>その他の操作</summary><button onClick={()=>run(exportCsv)}><Download size={18}/>CSV出力</button>{pending.length>0&&<button disabled={busy||!!job} onClick={()=>run(async()=>{const r=await api('/ocr/retry','POST');if(r)setJob(r)})}>未確認の写真を再読取</button>}<span>締切 11/3 23:59</span></details></>}
 {page==='review'&&<CodeReview ids={reviewIds} refresh={refresh} registerFlush={fn=>{detailFlush.current=fn}} canWrite={!!confirmed.length} onFinish={()=>startWriting()} onBack={()=>navigate('home')}/>}
 {page==='writing'&&<FreeTextReview ids={writingIds} tickets={tickets} boot={boot} refresh={refresh} registerFlush={fn=>{detailFlush.current=fn}} onExport={()=>startExport()} onSetup={()=>navigate('settings')}/>}
 {page==='profile'&&<section className="panel"><div className="form-grid profile-grid">{boot.schema.profile.map(([id,label,required])=><label key={id} htmlFor={id}><span className="field-label">{label}{required&&<em>必須</em>}</span>{boot.schema.selects[id]?<select id={id} value={profile[id]||''} onChange={e=>{setProfile({...profile,[id]:e.target.value});setDirty(true)}}><option value="">選択してください</option>{boot.schema.selects[id].map(o=><option key={o}>{o}</option>)}</select>:<input id={id} value={profile[id]||''} type={id==='c_q17'?'email':'text'} inputMode={id.startsWith('c_q1_')||id.startsWith('c_q9_')?'numeric':id==='c_q17'?'email':'text'} autoCapitalize={id==='c_q17'?'none':undefined} onChange={e=>{setProfile({...profile,[id]:e.target.value});setDirty(true)}}/>}</label>)}</div><div className="panel-footer"><button className="secondary" disabled={busy} onClick={()=>navigate('home')}>前に戻る</button></div></section>}
 {page==='survey'&&<section className="panel"><label className="field">希望キャラクター<select id="character" value={character} onChange={e=>{setCharacter(e.target.value);setDirty(true)}}><option value="">選択してください</option>{boot.schema.characters.map(c=><option key={c}>{c}</option>)}</select></label><Questions questions={boot.schema.questions} answers={answers} disabled={busy} onChange={a=>{setAnswers(a);setDirty(true)}} onPolish={polish}/><div className="panel-footer"><button className="secondary" disabled={busy} onClick={()=>navigate('home')}>前に戻る</button></div>{variants.length>0&&<details className="past-drafts"><summary>保存済みの下書き</summary>{variants.map((v,i)=><article key={i}>{boot.schema.questions.filter(q=>q.generate).map(q=><p key={q.id}>{q.label}<br/>{v[q.id]||'（空欄）'}</p>)}<button className="secondary" onClick={()=>{setAnswers({...answers,...Object.fromEntries(Object.entries(v).filter(([,value])=>typeof value==='string'&&value.trim()))});setDirty(true)}}>この下書きを使う</button></article>)}</details>}</section>}
 {page==='list'&&<>{!open?<><div className="search"><Search size={18}/><input aria-label="応募券を検索" placeholder="コード・写真名で検索" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="list-filter" aria-label="状態で絞り込み" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべて</option>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{visible.map(t=><div className="history-ticket-row" key={t.id}><button className="history-ticket" disabled={busy} onClick={()=>toggleTicket(t.id)}><img src={imageUrl(t.image)} alt="応募券"/><span><b className="serial">{t.code||'未読取'}</b><small>{t.filename}</small></span><span className={'badge '+t.state}>{states[t.state]}</span><ChevronRight size={17}/></button><button className="ticket-delete" disabled={busy} aria-label={(t.code||t.filename)+'を削除'} onClick={()=>void requestDelete(t)}><Trash2 size={19}/></button></div>)}{!visible.length&&<p className="muted">該当する応募券がありません。</p>}</>:<TicketDetail key={open} id={open} boot={boot} refresh={refresh} run={run} busy={busy} notify={notify} copy={copy} registerFlush={fn=>{detailFlush.current=fn}} onBack={()=>toggleTicket(open)} onDelete={()=>{const ticket=tickets.find(t=>t.id===open);if(ticket)void requestDelete(ticket)}} onExport={()=>startExport([open])}/>}</>}
 {page==='settings'&&<><PwaStatus/><StoragePanel/><BackupPanel disabled={busy||!!job} flush={async()=>{await auto.flush();await detailFlush.current?.()}}/><LlmPanel onChange={()=>setBoot(b=>b?{...b,llm:llmConfig()}:b)}/></>}
 </main></div>{exportIds&&<ShortcutExport ids={exportIds} onClose={()=>setExportIds(null)} onComplete={async()=>{await refresh();notify('ダウンロードを開始しました');setExportIds(null)}} onResolve={(target,field)=>{const ids=exportIds;setExportIds(null);if(target==='review')void startReview(ids.filter(id=>pending.some(t=>t.id===id)));else void navigate(target,field)}}/>}{draft&&<DraftReview draft={draft} label={boot.schema.questions.find(q=>q.id===draft.id)?.label||''} onClose={()=>setDraft(null)} onAccept={()=>{setAnswers({...answers,[draft.id]:draft.after});setDirty(true);setDraft(null)}}/>}{deleteTarget&&<DeleteTicketDialog ticket={deleteTarget} busy={busy} error={error} onCancel={()=>{setDeleteTarget(null);setError('')}} onDelete={()=>void deleteTicket()}/>} {toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}{page!=='home'&&page!=='review'&&page!=='writing'&&page!=='list'&&<SaveStatus save={auto}/>}</div>;
}

function DeleteTicketDialog({ticket,busy,error,onCancel,onDelete}:{ticket:TicketData,busy:boolean,error:string,onCancel:()=>void,onDelete:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);
 return <dialog ref={ref} className="shortcut-dialog delete-dialog" aria-labelledby="delete-title" onCancel={e=>{if(busy)e.preventDefault();else onCancel()}}><div className="shortcut-dialog-body"><h2 id="delete-title">この応募券を削除しますか？</h2><p className="serial">{ticket.code||ticket.filename}</p><p className="muted">この券の写真・回答・履歴を削除します。元には戻せません。</p>{error&&<p role="alert" className="alert">{error}</p>}<div className="delete-actions"><button className="secondary" disabled={busy} onClick={onCancel}>キャンセル</button><button className="danger" disabled={busy} onClick={onDelete}>{busy?'削除中…':'削除する'}</button></div></div></dialog>;
}

function DraftReview({draft,label,onClose,onAccept}:{draft:{before:string,after:string},label:string,onClose:()=>void,onAccept:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);
 return <dialog ref={ref} className="shortcut-dialog" onCancel={onClose} aria-label="文章の確認"><div className="shortcut-dialog-body"><h2>{label}</h2><label className="field">元の文章<textarea readOnly value={draft.before}/></label><label className="field">整えた文章<textarea readOnly value={draft.after}/></label><p className="muted">入力した文章をOpenAI APIへ送信して生成した候補です。</p><div className="draft-actions"><button className="secondary" onClick={onClose}>元のまま</button><button className="primary" onClick={onAccept}>この文章を使う</button></div></div></dialog>;
}

function CodeReview({ids,refresh,onFinish,onBack,canWrite,registerFlush}:{ids:string[],refresh:()=>Promise<void>,onFinish:()=>void,onBack:()=>void,canWrite:boolean,registerFlush:(fn:(()=>Promise<void>)|null)=>void}){
 const [index,setIndex]=useState(0),[t,setT]=useState<TicketData|null>(null),[code,setCode]=useState(''),[code2,setCode2]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[skipped,setSkipped]=useState(0),[dirty,setDirty]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setT(null);setError('');if(index>=ids.length)return;api('/tickets/'+ids[index]).then(x=>{if(active){setT(x);setCode(x.code);setCode2(x.code2);setDirty(false)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[index,ids,reload]);
 const auto=useAutosave({code,code2},dirty,!!t,async value=>{await api('/tickets/'+t!.id,'PUT',{...value,approved:false,character:t!.character_override||'',answers:t!.answer_overrides||{}});await refresh()},()=>setDirty(false));
 useEffect(()=>{registerFlush(auto.flush);return()=>{registerFlush(null)}},[]);
 const next=async(confirm:boolean)=>{if(!t)return;setBusy(true);setError('');try{await auto.flush();if(confirm){await api('/tickets/'+t.id+'/confirm','POST',{code,code2})}else{setSkipped(n=>n+1)}await refresh();setIndex(i=>i+1);window.scrollTo({top:0,behavior:'instant'})}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(index>=ids.length)return <section className="panel review-finished"><Check size={28}/><h2>確認が終わりました</h2>{skipped>0&&<p>あとで確認 {skipped}枚</p>}<button className="primary" disabled={!canWrite} onClick={onFinish}>自由記述へ<ChevronRight size={18}/></button><button className="secondary" onClick={onBack}>前に戻る</button></section>;
 return <section className="review-card"><div className="review-position">{index+1} / {ids.length}</div>{error&&<div className="alert" role="alert">{error}</div>}{t?<><a className="review-crop" href={imageUrl(t.image)} target="_blank" rel="noreferrer"><img src={imageUrl(t.crop||t.image)} alt="画像のシリアルコード"/></a><label className="field">シリアルコード①<input className="serial" autoCapitalize="characters" autoCorrect="off" spellCheck={false} disabled={busy} value={code} onChange={e=>{setCode(e.target.value);setDirty(true)}}/></label>{(!code||/[0O1I]/.test(code))&&<p className="muted">{code?'0とO・1とIを券面で確認してください。':t.note}</p>}<details className="review-original"><summary>原画像・コード②</summary><img src={imageUrl(t.image)} alt="原画像"/><label className="field">シリアルコード②<input disabled={busy} value={code2} autoCapitalize="none" autoCorrect="off" spellCheck={false} onChange={e=>{setCode2(e.target.value);setDirty(true)}}/></label></details><SaveStatus save={auto}/><div className="review-actions"><button className="primary" disabled={busy||!code.trim()} onClick={()=>void next(true)}>確認して次へ<ChevronRight size={18}/></button><button className="secondary" disabled={busy} onClick={()=>void next(false)}>あとで確認</button></div></>:error?<button className="secondary" onClick={()=>setReload(v=>v+1)}>再読み込み</button>:<p className="muted">読み込み中…</p>}</section>;
}

function FreeTextReview({ids,tickets,boot,refresh,registerFlush,onExport,onSetup}:{ids:string[],tickets:TicketData[],boot:Boot,refresh:()=>Promise<void>,registerFlush:(fn:(()=>Promise<void>)|null)=>void,onExport:()=>void,onSetup:()=>void}){
 const [index,setIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[blocked,setBlocked]=useState(true),[field,setField]=useState('c_q29');
 const flush=useRef<null|(()=>Promise<void>)>(null);
 const move=async(next:number)=>{setBusy(true);setError('');try{await flush.current?.();setIndex(next);window.scrollTo({top:0,behavior:'instant'})}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(!ids.length)return <section className="panel"><p>先にコードを確認してください。</p></section>;
 return <section className="writing-card">{error&&<div role="alert" className="alert">{error}</div>}<div className="writing-position"><span>{index+1} / {ids.length}枚</span><label>コードを選択<select aria-label="編集するコード" value={index} disabled={busy||blocked} onChange={e=>void move(Number(e.target.value))}>{ids.map((id,i)=><option value={i} key={id}>{i+1}. {tickets.find(t=>t.id===id)?.code||'未読取'}</option>)}</select></label></div><FreeTextTicket key={ids[index]} id={ids[index]} boot={boot} refresh={refresh} busy={busy} field={field} onFieldChange={setField} onBlocked={setBlocked} registerFlush={fn=>{flush.current=fn;registerFlush(fn)}} onSetup={onSetup}/><div className="writing-navigation"><button className="secondary" disabled={busy||blocked||index===0} onClick={()=>void move(index-1)}><ArrowLeft size={18}/>前のコード</button>{index<ids.length-1?<button className="primary" disabled={busy||blocked} onClick={()=>void move(index+1)}>次のコード<ChevronRight size={18}/></button>:<button className="primary" disabled={busy||blocked} onClick={onExport}>ZIPにまとめる<Download size={18}/></button>}</div></section>;
}

function FreeTextTicket({id,boot,refresh,busy,field,onFieldChange,onBlocked,registerFlush,onSetup}:{id:string,boot:Boot,refresh:()=>Promise<void>,busy:boolean,field:string,onFieldChange:(id:string)=>void,onBlocked:(blocked:boolean)=>void,registerFlush:(fn:(()=>Promise<void>)|null)=>void,onSetup:()=>void}){
 const [ticket,setTicket]=useState<TicketData|null>(null),[overrides,setOverrides]=useState<Answers>({}),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0),[generating,setGenerating]=useState(false),[draft,setDraft]=useState<{id:string,before:string,after:string}|null>(null);
 useEffect(()=>{let active=true;setError('');api('/tickets/'+id).then(t=>{if(active){setTicket(t);setOverrides(t.answer_overrides||{});setDirty(false)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[id,reload]);
 const auto=useAutosave(overrides,dirty,!!ticket,async answers=>{await api('/tickets/'+id,'PUT',{code:ticket!.code,code2:ticket!.code2,approved:!!ticket!.approved,character:ticket!.character_override||'',answers});await refresh()},()=>setDirty(false));
 useEffect(()=>{registerFlush(auto.flush);return()=>registerFlush(null)},[]);
 const effective={...(boot.survey.answers||{}),...overrides};
 const locked=!!ticket&&(!ticket.approved||['done','unknown'].includes(ticket.state));
 useEffect(()=>{onBlocked(!ticket||generating||locked||!!draft);return()=>onBlocked(true)},[!!ticket,generating,locked,!!draft]);
 const disabled=busy||generating||locked;
 const polish=async(field:string)=>{if(!boot.llm.has_key){onSetup();return}const before=String(effective[field]||'');if(!before.trim()){setError('文章の元になる感想・要望を入力してください');return}setGenerating(true);setError('');try{await auto.flush();const result=await api('/generate','POST',{notes:{[field]:before},count:1,max_length:250});setDraft({id:field,before,after:result.variants[0][field]})}catch(e){setError((e as Error).message)}finally{setGenerating(false)}};
 const questions=['c_q29','c_q30','c_q31','c_q21'].map(id=>boot.schema.questions.find(q=>q.id===id)!).filter(Boolean);
 return <>{error&&<div role="alert" className="alert">{error}{!ticket&&<button onClick={()=>setReload(n=>n+1)}>再読み込み</button>}</div>}{ticket?<><div className="writing-code"><strong className="serial">{ticket.code}</strong><small>{ticket.character}</small></div>{locked&&<p role="alert" className="ticket-note">この券は編集できません。コードの確認状態を一覧で確認してください。</p>}<div className="writing-tabs" role="tablist" aria-label="自由記述の項目">{questions.map(q=><button key={q.id} id={'tab-'+q.id} role="tab" aria-selected={field===q.id} aria-controls={'panel-'+q.id} disabled={disabled} onClick={()=>onFieldChange(q.id)}>{q.id==='c_q29'?'感想':q.id==='c_q30'?'イベント':q.id==='c_q31'?'新商品':'作品'}</button>)}</div><div className="writing-fields">{questions.filter(q=>q.id===field).map(q=><div className="writing-field" role="tabpanel" aria-labelledby={'tab-'+q.id} id={'panel-'+q.id} key={q.id}><div className="writing-field-label"><label htmlFor={'write-'+q.id}>{q.label}</label><small>{Object.prototype.hasOwnProperty.call(overrides,q.id)?'個別':'共通'}</small></div><textarea id={'write-'+q.id} rows={5} maxLength={4000} disabled={disabled} value={String(effective[q.id]||'')} onChange={e=>{setOverrides({...overrides,[q.id]:e.target.value});setDirty(true)}}/><div className="writing-field-actions">{Object.prototype.hasOwnProperty.call(overrides,q.id)&&<button disabled={disabled} onClick={()=>{const next={...overrides};delete next[q.id];setOverrides(next);setDirty(true)}}>共通に戻す</button>}{q.generate&&<button className="polish-button" disabled={disabled||!String(effective[q.id]||'').trim()} onClick={()=>void polish(q.id)}><Sparkles size={16}/>{generating?'文章を整えています…':'文章を整える'}</button>}</div></div>)}</div><SaveStatus save={auto}/></>:!error&&<p className="muted">読み込み中…</p>}{draft&&<DraftReview draft={draft} label={questions.find(q=>q.id===draft.id)?.label||''} onClose={()=>setDraft(null)} onAccept={()=>{setOverrides({...overrides,[draft.id]:draft.after});setDirty(true);setDraft(null)}}/>}</>;
}

type ExportPlan={fingerprint:string,mode:string,count:number,ticket_count:number,skipped:number,unconfirmed:number,excluded:number,issues:{page:string,id?:string,message:string}[],entries:{line:number,code:string,filename:string,label:string,value:string}[]};
function ShortcutExport({ids,onClose,onComplete,onResolve}:{ids:string[],onClose:()=>void,onComplete:()=>Promise<void>,onResolve:(page:string,field?:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [mode,setMode]=useState('fields'),[exclude,setExclude]=useState(false),[plan,setPlan]=useState<ExportPlan|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{dialog.current?.showModal()},[]);
 useEffect(()=>{let active=true;setPlan(null);setError('');api('/shortcuts/preview','POST',{mode,ids,exclude_unconfirmed:exclude}).then(p=>{if(active)setPlan(p)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[mode,ids,exclude,version]);
 const download=async()=>{setBusy(true);setError('');try{
  const blob=await exportZip({mode:mode as 'fields'|'codes',ids,exclude_unconfirmed:exclude,fingerprint:plan?.fingerprint});saveDownload(blob,'ouboken-shortcuts.zip');await onComplete();
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <dialog ref={dialog} className="shortcut-dialog" onCancel={e=>{if(busy)e.preventDefault();else onClose()}} aria-labelledby="shortcut-title"><div className="shortcut-dialog-body"><div className="section-title"><h2 id="shortcut-title">ZIPにまとめる</h2><button className="icon-button" aria-label="閉じる" disabled={busy} onClick={onClose}><X size={20}/></button></div><label className="field">内容<select value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><option value="fields">コード・住所・自由記述</option><option value="codes">シリアルコード①のみ</option></select></label>{error&&<div role="alert" className="alert">{error}<button onClick={()=>setVersion(v=>v+1)}>再確認</button></div>}{plan?<>{plan.issues.length>0&&<div className="export-issues">{plan.issues.map((issue,i)=><button key={i} onClick={()=>onResolve(issue.page,issue.id)}>{issue.message}<ChevronRight size={18}/></button>)}</div>}{plan.unconfirmed>0&&<label className="check-line"><input type="checkbox" disabled={busy} checked={exclude} onChange={e=>setExclude(e.target.checked)}/>未確認 {plan.unconfirmed}枚を今回は含めない</label>}<div className="export-count"><strong>{plan.ticket_count}枚 / {plan.count}行</strong>{plan.excluded>0&&<span>応募済み・結果不明 {plan.excluded}枚を除外</span>}</div>{plan.count>0&&<details className="export-preview"><summary>出力する内容</summary><ol>{plan.entries.map(e=><li key={e.line}><small>{e.code} · {e.label}</small><p>{e.value}</p></li>)}</ol></details>}{!plan.count&&!plan.issues.length&&<p className="muted">出力対象の券がありません。</p>}</>:<p className="muted">確認中…</p>}<button className="primary export-download" disabled={busy||!plan?.count||!!plan.issues.length} onClick={()=>void download()}><Download size={18}/>{busy?'出力中…':'ファイルを出力'}</button>{mode==='fields'&&<p className="muted">住所・電話番号を含みます。選択式回答は手動で選択します。</p>}</div></dialog>;
}
function PageTitle({title}:{title:string}){return <div className="page-title"><h1>{title}</h1></div>}
function MultiOptions({compact,label,selected,children}:{compact:boolean,label:string,selected:string[],children:React.ReactNode}){
 const menu=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{
  const outside=(e:PointerEvent)=>{if(menu.current&&!menu.current.contains(e.target as Node))menu.current.open=false};
  const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&menu.current?.open){menu.current.open=false;menu.current.querySelector('summary')?.focus()}};
  document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);
  return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)};
 },[]);
 if(!compact)return <>{children}</>;
 return <details ref={menu} className="multi-select"><summary aria-label={label+'（複数選択）'}><span>{selected.length?selected.join('、'):'未回答'}</span><small>{selected.length?`${selected.length}件`: '複数選択'}</small><ChevronDown size={16}/></summary><div className="multi-select-menu">{children}</div></details>
}
function Questions({questions,answers,onChange,disabled=false,onPolish}:{questions:Question[],answers:Answers,onChange:(a:Answers)=>void,disabled?:boolean,onPolish?:(id:string)=>void}){return <div className="questions">{questions.filter(q=>q.id!=='c_q26'||answers.c_q25==='サイトは見たが購入には至らなかった').map(q=><div className="question" key={q.id}><label htmlFor={q.id}>{q.label}</label>{q.type==='text'?<textarea id={q.id} disabled={disabled} value={String(answers[q.id]||'')} onChange={e=>onChange({...answers,[q.id]:e.target.value})} rows={q.generate?3:2}/>:q.type==='single'?<select id={q.id} disabled={disabled} value={String(answers[q.id]||'')} onChange={e=>onChange({...answers,[q.id]:e.target.value,...(q.id==='c_q25'&&e.target.value!=='サイトは見たが購入には至らなかった'?{c_q26:[],c_q26_etc:''}:{})})}><option value="">未回答</option>{q.options?.map(o=><option key={o}>{o}</option>)}</select>:<MultiOptions compact={['c_q23','c_q24'].includes(q.id)} label={q.label} selected={Array.isArray(answers[q.id])?answers[q.id] as string[]:[]}><div className="options">{q.options?.map(o=><label key={o}><input type="checkbox" disabled={disabled} checked={Array.isArray(answers[q.id])&&(answers[q.id] as string[]).includes(o)} onChange={e=>{const before=Array.isArray(answers[q.id])?answers[q.id] as string[]:[];onChange({...answers,[q.id]:e.target.checked?[...before,o]:before.filter(x=>x!==o)})}}/>{o}</label>)}</div></MultiOptions>}{q.generate&&onPolish&&<button className="polish-button" disabled={disabled} onClick={()=>onPolish(q.id)}><Sparkles size={16}/>文章を整える</button>}{(answers[q.id]==='その他'||Array.isArray(answers[q.id])&&(answers[q.id] as string[]).includes('その他'))&&<input disabled={disabled} aria-label={q.label+' その他の内容'} placeholder="その他の内容" maxLength={255} value={String(answers[q.id+'_etc']||'')} onChange={e=>onChange({...answers,[q.id+'_etc']:e.target.value})}/>}</div>)}</div>}
function TicketDetail({id,boot,refresh,run,busy,notify,copy,registerFlush,onBack,onExport,onDelete}:{id:string,boot:Boot,refresh:()=>Promise<void>,run:(fn:()=>Promise<void>)=>Promise<void>,busy:boolean,notify:(s:string)=>void,copy:(s:string)=>Promise<void>,registerFlush:(fn:(()=>Promise<void>)|null)=>void,onBack:()=>void,onExport:()=>void,onDelete:()=>void}){
 const [t,setT]=useState<TicketData|null>(null),[code,setCode]=useState(''),[code2,setCode2]=useState(''),[character,setCharacter]=useState(''),[answers,setAnswers]=useState<Answers>({}),[approved,setApproved]=useState(false),[dirty,setDirty]=useState(false),[detailDraft,setDetailDraft]=useState<{id:string,before:string,after:string}|null>(null);
 const load=async()=>{const x=await api('/tickets/'+id);setT(x);setCode(x.code);setCode2(x.code2);setCharacter(x.character_override||'');setAnswers(x.answer_overrides||{});setApproved(!!x.approved);setDirty(false)};
 useEffect(()=>{run(load)},[id]);
 const auto=useAutosave({code,code2,character,answers,approved},dirty,!!t,async value=>{
  await api('/tickets/'+id,'PUT',value);
  setT(await api('/tickets/'+id));await refresh();
 },()=>setDirty(false));
 const save=auto.flush;
 useEffect(()=>{registerFlush(save);return()=>{registerFlush(null);void save().catch(()=>{})}},[]);
 if(!t)return <div className="detail">読み込み中…</div>;
 const locked=['done','unknown'].includes(t.state);
 const payload=t.payload;
 const effectiveAnswers=locked?(t.payload?.answers||t.answers):{...(boot.survey.answers||{}),...answers};
 const fields=payload?[['シリアルコード①',payload.code],['シリアルコード②',payload.code2],...boot.schema.profile.map(([k,label])=>[label,payload.profile[k]||'']),['希望キャラクター',payload.character],...boot.schema.questions.filter(q=>q.id!=='c_q26'||payload.answers.c_q25==='サイトは見たが購入には至らなかった').map(q=>[q.label,Array.isArray(payload.answers[q.id])?(payload.answers[q.id] as string[]).join('、'):String(payload.answers[q.id]||'')]),...boot.schema.questions.filter(q=>payload.answers[q.id+'_etc']&&(payload.answers[q.id]==='その他'||Array.isArray(payload.answers[q.id])&&(payload.answers[q.id] as string[]).includes('その他'))).map(q=>[q.label+'（その他）',String(payload.answers[q.id+'_etc'])])]:[];
 return <div className="detail"><div className="detail-heading"><strong className="serial">{t.code||'未読取'}</strong><span className={'badge '+t.state}>{states[t.state]}</span></div><label className="field status-control">ステータス<select aria-label="ステータス" disabled={busy} value={t.state} onChange={e=>{const state=e.target.value;void run(async()=>{await auto.flush();await api('/tickets/'+id+'/status','POST',{state});await load();await refresh();notify('ステータスを変更しました')})}}>{Object.entries(states).map(([state,label])=><option key={state} value={state} disabled={state==='ready'&&!t.approved||['prepared','done','unknown'].includes(state)&&!t.payload&&t.history?.[0]?.state!=='exported_codes'&&state!==t.state}>{label}</option>)}</select></label>{locked&&<p className="muted">「確認済み」に戻すと内容を編集できます。</p>}<details className="detail-code"><summary>画像・コード・キャラクター</summary><div className="detail-top"><div className="photo-review"><a href={imageUrl(t.image)} target="_blank" rel="noreferrer"><img src={imageUrl(t.image)} alt={t.filename+' 原画像'}/><span>原画像を拡大 <ArrowUpRight size={14}/></span></a><div className="crop"><small>読み取ったコードの部分</small><img src={imageUrl(t.crop)} alt="コードの切り抜き"/></div></div><div className="code-review"><h3>コードの確認</h3><p className="muted">O / 0・I / 1などの読み違いを確認してください。</p>{t.note&&t.note!=='画像とコードを照合してください。'&&<p className="ticket-note">{t.note}</p>}<div className="form-grid"><label>シリアルコード①<input className="serial" autoCapitalize="characters" autoCorrect="off" spellCheck={false} disabled={locked} value={code} onChange={e=>{setCode(e.target.value);setApproved(false);setDirty(true)}}/></label><label>シリアルコード②<input autoCapitalize="none" autoCorrect="off" spellCheck={false} disabled={locked} value={code2} onChange={e=>{setCode2(e.target.value);setApproved(false);setDirty(true)}}/></label></div><label className="check-line"><input type="checkbox" disabled={locked} checked={approved} onChange={e=>{setApproved(e.target.checked);setDirty(true)}}/>画像とコードを照合済み</label><label className="field">希望キャラクター<select disabled={locked} value={locked?t.character:character} onChange={e=>{setCharacter(e.target.value);setDirty(true)}}><option value="">{locked?'（記録なし）':`共通設定：${boot.survey.character||'未設定'}`}</option>{boot.schema.characters.map(c=><option key={c}>{c}</option>)}</select></label></div></div></details>
 <details className="answer-details"><summary>アンケート <span>{locked?'記録済み':Object.keys(answers).length?'個別の変更あり':'共通回答'} <ChevronDown size={15}/></span></summary><div className="answer-body">{!locked&&(Object.keys(answers).length>0||!!character)&&<button className="secondary" onClick={()=>{setAnswers({});setCharacter('');setDirty(true)}}>個別の変更を解除</button>}<Questions questions={boot.schema.questions} answers={effectiveAnswers} disabled={locked||busy} onPolish={field=>void run(async()=>{if(!boot.llm.has_key)throw Error('設定でOpenAI APIキーを入力してください');const before=String(effectiveAnswers[field]||'');if(!before.trim())throw Error('文章の元になる感想・要望を入力してください');await auto.flush();const result=await api('/generate','POST',{notes:{[field]:before},count:1,max_length:250});setDetailDraft({id:field,before,after:result.variants[0][field]})})} onChange={next=>{const changed=Object.fromEntries(Object.entries(next).filter(([key,value])=>JSON.stringify(value)!==JSON.stringify(effectiveAnswers[key])));setAnswers({...answers,...changed});setDirty(true)}}/></div></details>
 <div className="detail-save"><SaveStatus save={auto}/><button className="secondary" disabled={busy} onClick={onBack}>一覧に戻る</button>{!locked&&<button className="primary" disabled={busy} onClick={onExport}>この券を出力</button>}</div>
 {payload&&<details className="copy-details"><summary>保存内容・コピー <span><ChevronDown size={15}/></span></summary><div className="copy-body"><div className="copy-intro"><button className="secondary" disabled={dirty} onClick={()=>copy(fields.map(([k,v])=>`${k}: ${v}`).join('\n'))}><Copy size={15}/>全項目をコピー</button></div>{dirty&&<p className="ticket-note">変更を自動保存中です。再出力するとコピー内容を更新します。</p>}<div className="copy-grid">{fields.map(([label,value])=><div className="copy-field" key={label}><div><small>{label}</small><p>{value||'（空欄）'}</p></div><button className="icon-button" disabled={!value||dirty} aria-label={label+'をコピー'} onClick={()=>copy(value)}><Copy size={16}/></button></div>)}</div><a className="external-link" href={boot.schema.url} target="_blank" rel="noreferrer">応募ページを開く<ArrowUpRight size={16}/></a></div></details>}
 {detailDraft&&<DraftReview draft={detailDraft} label={boot.schema.questions.find(q=>q.id===detailDraft.id)?.label||''} onClose={()=>setDetailDraft(null)} onAccept={()=>{setAnswers({...answers,[detailDraft.id]:detailDraft.after});setDirty(true);setDetailDraft(null)}}/>}
 <button className="detail-delete" disabled={busy} onClick={onDelete}><Trash2 size={18}/>この応募券を削除</button>
 <details className="history"><summary>操作履歴（{t.history?.length||0}件）</summary>{t.history?.map((h,i)=><div className="history-entry" key={i}><time>{h.created} UTC</time>{h.note}{h.snapshot&&<details><summary>この時点で保存した内容を見る</summary><div className="history-snapshot"><p>コード①: {h.snapshot.code}<br/>コード②: {h.snapshot.code2}<br/>希望キャラクター: {h.snapshot.character}</p>{boot.schema.profile.map(([k,label])=><p key={k}>{label}: {h.snapshot!.profile[k]||'（空欄）'}</p>)}{boot.schema.questions.map(q=><p key={q.id}>{q.label}: {Array.isArray(h.snapshot!.answers[q.id])?(h.snapshot!.answers[q.id] as string[]).join('、'):String(h.snapshot!.answers[q.id]||'（空欄）')}</p>)}</div></details>}</div>)}</details>
 </div>
}
startPwa();
createRoot(document.getElementById('root')!).render(<App/>);
