import {useEffect,useState,useRef} from 'react';
import {appScope,deleteAppCaches,inspectStorage,workerRequest} from './storage-health';
export function useStorageWarnings(){
 const [messages,setMessages]=useState<string[]>([]);
 useEffect(()=>{let alive=true,timer:ReturnType<typeof setTimeout>|undefined;const check=()=>{clearTimeout(timer);timer=setTimeout(()=>{void inspectStorage().then(r=>{if(alive)setMessages(r.messages)}).catch(()=>{if(alive)setMessages(['保存データを確認できませんでした。設定で容量を再確認してください。'])})},400)};
  const visible=()=>{if(document.visibilityState==='visible')check()};check();window.addEventListener('focus',check);window.addEventListener('ouboken-data-changed',check);window.addEventListener('ouboken-pwa-status',check);window.addEventListener('storage',check);document.addEventListener('visibilitychange',visible);
  return()=>{alive=false;clearTimeout(timer);window.removeEventListener('focus',check);window.removeEventListener('ouboken-data-changed',check);window.removeEventListener('ouboken-pwa-status',check);window.removeEventListener('storage',check);document.removeEventListener('visibilitychange',visible)};
 },[]);return messages;
}
const size=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
export function StoragePanel(){
 const [value,setValue]=useState<Awaited<ReturnType<typeof inspectStorage>>|null>(null),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 const run=async(action?:()=>Promise<void>)=>{setBusy(true);setError('');try{await action?.();setValue(await inspectStorage(true));window.dispatchEvent(new Event('ouboken-pwa-status'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{void run()},[]);useEffect(()=>{if(confirm)dialog.current?.showModal()},[confirm]);
 return <section className="panel"><h2>端末の保存容量</h2><dl className="storage-sizes"><div><dt>合計（概算）</dt><dd>{value?size(value.total):'確認中…'}</dd></div><div><dt>アプリ・OCRキャッシュ</dt><dd>{value?size(value.cacheBytes):'—'}</dd></div><div><dt>写真・回答・履歴</dt><dd>{value?size(value.dataBytes):'—'}</dd></div></dl>{busy&&<p role="status" className="muted">処理中…</p>}<div className="storage-actions"><button className="secondary" disabled={busy} onClick={()=>void run()}>容量を再確認</button><button className="secondary" disabled={busy||!value?.cacheBytes} onClick={()=>setConfirm(true)}>キャッシュを削除</button><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{if(!navigator.onLine)throw Error('オンラインで再準備してください');const result=await workerRequest('REPAIR');if(!result)throw Error('アプリを更新してから再準備してください');if(result.missing.length)throw Error('ファイルの準備が完了していません');setMessage('キャッシュを再準備しました。')})}>キャッシュを再準備</button></div><p className="muted">キャッシュ削除後も写真・回答は残ります。オフラインで使う前に再準備してください。</p><details><summary>欠損チェックについて</summary><p className="muted">写真とオフライン用ファイルを起動時・画面に戻った際に確認します。すべての保存データと検知記録が同時に消去されると、消去を検知できません。容量はファイル本体の合計で、ブラウザ内部の管理領域を含みません。</p></details>{message&&<p role="status" className="muted">{message}</p>}{error&&<p role="alert" className="save-error">{error}</p>}{confirm&&<dialog ref={dialog} className="shortcut-dialog" aria-label="キャッシュの削除" onCancel={()=>setConfirm(false)}><div className="shortcut-dialog-body"><h2>キャッシュを削除しますか？</h2><p>写真・回答・履歴は残ります。オフライン利用と画像の読み取りに必要なファイルを削除します。</p><div className="delete-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>キャンセル</button><button className="danger" disabled={busy} onClick={()=>void run(async()=>{await deleteAppCaches(caches,appScope());setConfirm(false);setMessage('キャッシュを削除しました。オンラインで再準備できます。')})}>削除する</button></div>{error&&<p role="alert">{error}</p>}</div></dialog>}</section>;
}
